kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-app
    spec:
      volumes:
        - name: my-volume
          emptyDir: {}
        - name: host-volume
          persistentVolumeClaim:
            claimName: registry-test-frontend-pvc
        - name: hosts-volume
          persistentVolumeClaim:
            claimName: registry-test-frontend-data-pvc
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: frontend-app
          env:
            - name: d
              value: d
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: my-volume
              mountPath: /data
            - name: host-volume
              mountPath: /etc/nginx/conf.d/
            - name: hosts-volume
              mountPath: /usr/share/nginx/html/eoffice/
          terminationMessagePolicy: File
          image: 'registry.ocp4.pacosta.com:8443/test/frontendeoffice:8'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 13
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-08-09T10:43:08Z'
      lastTransitionTime: '2023-08-01T07:28:58Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "frontend-deployment-5b587f9c9c" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-08-17T08:10:31Z'
      lastTransitionTime: '2023-08-17T08:10:31Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
